#ifndef OMCBDA_H
#define OMCBDA_H

// {7DB2DEEA-42B4-423d-A2F7-19C32E51CCC1}
static const GUID KSPROPSETID_OMCDiSEqCProperties = { 0x7DB2DEEA, 0x42B4, 0x423d, { 0xA2, 0xF7, 0x19, 0xC3, 0x2E, 0x51, 0xCC, 0xC1}};

typedef enum {
	KSPROPERTY_OMC_DISEQC_WRITE,
	KSPROPERTY_OMC_DISEQC_READ,
	KSPROPERTY_OMC_DISEQC_SET22K
} KSPROPERTY_OMC_DISEQC;

typedef struct _OMC_BDA_DISEQC_DATA {
	ULONG     nLen;
	UCHAR     pBuffer[64];
	ULONG     nRepeatCount;
} OMC_BDA_DISEQC_DATA, *POMC_BDA_DISEQC_DATA;

#endif //OMCBDA_H
