#ifndef OMCBDA_H
#define OMCBDA_H

#include <ks.h>

DEFINE_GUIDSTRUCT("7DB2DEEA-42B4-423d-A2F7-19C32E51CCC1", KSPROPSETID_OmcDiSEqCProperties);
#define KSPROPSETID_OmcDiSEqCProperties DEFINE_GUIDNAMED(KSPROPSETID_OmcDiSEqCProperties)

typedef enum _KSPROPERTY_OMC_DISEQC
{
	KSPROPERTY_OMC_DISEQC_WRITE	= 0,
	KSPROPERTY_OMC_DISEQC_READ,				
	KSPROPERTY_OMC_DISEQC_SET22K,
	KSPROPERTY_OMC_DISEQC_ENCABLOSSCOMP,
	KSPROPERTY_OMC_DISEQC_TONEBURST
}KSPROPERTY_OMC_DISEQC;

typedef struct _OMC_BDA_DISEQC_DATA
{
	ULONG			nLen;
	UCHAR			pBuffer[64];
	ULONG			nRepeatCount;
}OMC_BDA_DISEQC_DATA, *POMC_BDA_DISEQC_DATA;

#endif //OMCBDA_H
